global:
  scrape_interval:     1s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'frontend'
    static_configs:
      - targets: ['localhost:5000']
  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:5001']
